apiVersion: v1
kind: ConfigMap
metadata:
  name: royal-dispatch-config
  namespace: royal-dispatch
data:
  S3_PUBLIC_URL: "https://minio.quybits.com"
  NEXT_PUBLIC_FRONTEND_URL: "https://royal-dispatch.quybits.com"
