apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  values:
    persistence:
      storageClassName: local-path
    grafana.ini:
      server:
        root_url: "%(protocol)s://%(domain)s:%(http_port)s/"
