apiVersion: v1
kind: ConfigMap
metadata:
  name: royal-dispatch-config
  namespace: royal-dispatch
data:
  S3_PUBLIC_URL: "https://minio.homelander.local"
  NEXT_PUBLIC_FRONTEND_URL: "https://royal-dispatch.lab.quybits.com"
  BACKEND_PUBLIC_URL: "https://royal-dispatch.lab.quybits.com"
