apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepository.yaml
  - externalsecret.yaml
  - helmrelease.yaml
  - ingress.yaml
namespace: grafana
configMapGenerator:
  - name: grafana-royal-dispatch-dashboard
    files:
      - royal-dispatch.json=dashboards/royal-dispatch.json
    options:
      labels:
        grafana_dashboard: "1"
generatorOptions:
  disableNameSuffixHash: true
