apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: personal-site-postgres
  namespace: personal-site
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: personal-site-postgres
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: personal-site/postgres
        property: username
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: personal-site/postgres
        property: password
    - secretKey: POSTGRES_DSN
      remoteRef:
        key: personal-site/postgres
        property: dsn
