apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: personal-site
  namespace: flux-system
spec:
  image: quydoan/personal-site
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: personal-site
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: personal-site
  filterTags:
    pattern: '^[a-f0-9]+-(?P<ts>[0-9]+)$'
    extract: '$ts'
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: personal-site
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@users.noreply.github.com
      messageTemplate: |
        chore: update personal-site image

        {{range .Changed.Changes}}
        - {{.OldValue}} -> {{.NewValue}}
        {{end}}
    push:
      branch: main
  update:
    path: ./apps/personal-site
    strategy: Setters
