apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap-env.yaml
  - externalsecret.yaml
  - externalsecret-postgres.yaml
  - postgres-initsql-configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - ingest-job.yaml
  - image-automation.yaml
