apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-secrets
  namespace: minio
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: minio-secrets
    creationPolicy: Owner
  data:
    - secretKey: root-user
      remoteRef:
        key: minio
        property: root_user
    - secretKey: root-password
      remoteRef:
        key: minio
        property: root_password
