apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n
  namespace: n8n
spec:
  tls:
    - hosts:
        - n8n.quybits.com
      secretName: n8n-tls
  rules:
    - host: n8n.quybits.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: n8n
                port:
                  number: 80
