apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: royal-dispatch
  labels:
    app: royal-dispatch
    component: backend
spec:
  selector:
    app: royal-dispatch
    component: backend
  ports:
    - port: 8000
      targetPort: 8000
