apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: royal-dispatch-secrets
  namespace: royal-dispatch
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: royal-dispatch-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: royal-dispatch
