apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: royal-dispatch
  labels:
    app: royal-dispatch
    component: frontend
spec:
  selector:
    app: royal-dispatch
    component: frontend
  ports:
    - port: 3000
      targetPort: 3000
