apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: n8n
spec:
  values:
    main:
      persistence:
        storageClass: local-path
      extraEnv:
        WEBHOOK_URL: "https://n8n.homelander.local/"
        N8N_EDITOR_BASE_URL: "https://n8n.homelander.local/"
        THE_ROYAL_DISPATCH_API_URL: "http://backend.royal-dispatch.svc.cluster.local:8000"
